### ISSUE TITLE
“Success Stories” page blank after import

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-law-pro#2]
The /success-stories/ page (linked from the footer) is empty after importing demo content. 

Should it contain placeholder text?

**Comment by JiveDig** [comment]
Yes, we're either getting rid of that page or going to add some sample content. Leave this open so we deal with it before launch.

**Comment by JiveDig** [comment]
Added dummy content. May end up putting actual reviews/testimonials of Mai Theme there too.
