### ISSUE TITLE
“No Fields Found” in Free Consultation HTML widget

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-law-pro#4]
The imported “Free Consultation” widget ends with “no fields found” text due to a missing Ninja Form of ID=2.

<img width="412" alt="customize__news" src="https://user-images.githubusercontent.com/647669/46747273-219cc500-ccb1-11e8-9081-59f71c9d44ad.png">

Perhaps give the imported demo content an ID of 1 instead?

```
[callout bg="323232" class="text-xs-center"]
<h2>Free Consultation!</h2>
This is a great Call To Action. You can put whatever you'd like here, and change the background color to whatever you'd like.
[ninja_form id=1]
[/callout]
```

That way it would use the default “contact me” form that Ninja Forms sets up on install.

**Comment by JiveDig** [comment]
Good call. Just a note, I'm not sure if the new Mai Configurations plugin will be ready for launch because of things like this. I was considering importing the forms too, but it would get tricky with all the configurations.

**Comment by nickcernis** [comment]
Understood, and you've done a great job with it so far!

**Comment by JiveDig** [comment]
This is a weird one, because currently (and strangely) Ninja Forms doesn't allow the same form multiple times on a single page. See https://github.com/wpninjas/ninja-forms/issues/1730. I'm not sure what's worse, the form spinning cause it's trying to load 2, or seeing No Fields Found and telling people to create a new form.

**Comment by nickcernis** [comment]
>  No Fields Found and telling people to create a new form.

That sounds like it may be a better approach, since it's likely easier to debug. Feel free to close this if you want to handle with docs/via support for now.

**Comment by JiveDig** [comment]
Thanks for the follow up. Will do.
