### ISSUE TITLE
Footer text contrast

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-law-pro#5]
Footer contrast text seems low. I'd suggest increasing contrast given its size and use for legal text on a legal site.

<img width="765" alt="news" src="https://user-images.githubusercontent.com/647669/46749497-2c0d8d80-ccb6-11e8-966e-ad84eb168214.png">

**Comment by JiveDig** [comment]
I made this a bit lighter in a minor update to Mai THeme Engine plugin.
