### ISSUE TITLE
Text contrast on “required field”

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-law-pro#6]
“Required field” text is hard to read at present (Home 2, “schedule a no-cost consultation” widget):

<img width="628" alt="home_two" src="https://user-images.githubusercontent.com/647669/46750050-6166ab00-ccb7-11e8-8b2c-ad39b0a7f368.png">

**Comment by JiveDig** [comment]
I think these are a bit of edge-case styles since many people won't use Ninja Forms or won't use required fields. I don't think I want to support styles for all the form plugins and all that, so I made those fields _not_ required to avoid this altogether.
