### ISSUE TITLE
Footer link double underline on hover

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-law-pro#7]
Flagging because other links within main content don't display this issue.

![screen shot on 2018-10-11 at 17 51 03](https://user-images.githubusercontent.com/647669/46816908-3bf0a480-cd7e-11e8-8ac5-384014aef947.png)

**Comment by JiveDig** [comment]
Good catch. This is a bug i've seen a handful of times and forgot to open an issue for. I'll fix that one up.

**Comment by JiveDig** [comment]
Fixed in the minor update to Mai Theme Engine plugin.
